name: yard-dev

services:
  db:
    image: postgres:latest
    container_name: yard-dev-db
    environment:
      POSTGRES_USER: yard
      POSTGRES_DB: yard-dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./.db:/var/lib/postgresql/data
